// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts
/*
If you want to add custom formats, create a file in this folder named: "custom-formats.ts"

Paste the following code into the file and add your desired formats and their sections between the brackets:
--------------------------------------------------------------------------------
// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts

export const Formats: FormatList = [
];
--------------------------------------------------------------------------------

If you specify a section that already exists, your format will be added to the bottom of that section.
New sections will be added to the bottom of the specified column.
The column value will be ignored for repeat sections.
*/

export const Formats: FormatList = [
	// National Dex
	///////////////////////////////////////////////////////////////////

	{
		section: "Souls",
	},
	{
			name: "[Gen 9] Random Battle",
			desc: `Randomized teams of Pok&eacute;mon with sets that are generated to be competitively viable.`,
			mod: 'gen9',
			team: 'random',
			ruleset: ["Terastal Clause",'PotD', 'Obtainable', 'Species Clause', 'HP Percentage Mod', 'Cancel Mod', 'Sleep Clause Mod', 'Illusion Level Mod'],
		},
	{
		name: "[Gen 9] National Dex",
		mod: "gen9",
		ruleset: [
			"Standard NatDex",
			"Baton Pass Stat Trap Clause",
			"OHKO Clause",
			"Evasion Clause",
			"Species Clause",
			"Sleep Moves Clause",
			"Terastal Clause",
		],
		banlist: [
			"ND Uber",
			"ND AG",
			"Arena Trap",
			"Moody",
			"Power Construct",
			"Shadow Tag",
			"King's Rock",
			"Quick Claw",
			"Razor Fang",
			"Assist",
			"Last Respects",
			"Shed Tail",
		],
	},
	{
		name: "[Gen 9] National Dex Ubers",
		mod: "gen9",
		ruleset: [
			"Standard NatDex",
			"Baton Pass Stat Trap Clause",
			"OHKO Clause",
			"Evasion Moves Clause",
			"Evasion Items Clause",
			"Species Clause",
			"Sleep Moves Clause",
			"Mega Rayquaza Clause",
			"Terastal Clause",
		],
		banlist: [
			"ND AG",
			"Assist",
		],
	},
	{
		name: "[Gen 9] National Dex Ubers UU",
		mod: "gen9",
		ruleset: [
			"[Gen 9] National Dex Ubers", "!Sleep Moves Clause", 'Sleep Clause Mod'
		],
		banlist: [
			"Arceus",
			"Marshadow",
			"Calyrex-Ice",
			"Chien-Pao",
			"Deoxys-Attack",
			"Eternatus",
			"Frostikenite",
			"Griseous Core",
			"Red Orb",
			"Ho-Oh",
			"Blue Orb",
			"Necrozma-Dusk-Mane",
			"Ultranecrozium Z",
			"Rayquaza",
			"Salamencite",
			"Xerneas",
			"Yveltal",
			"Kyurem-Black",
			"Rusted Sword",
			"Power Construct",
			"Shadow Tag",
			"King's Rock",
			"Razor Fang",
			"Last Respects",
			"Mewtwonite Y",
			"Caimanragonite",
			"Cereblazite",
			"Tempervianite"
		],
	},
	{
		name: "[Gen 9] National Dex UU",
		mod: "gen9",
		ruleset: ["[Gen 9] National Dex"],
		banlist: [
			"ND OU",
			"ND UUBL",
			"Drizzle"
		],
	},
	{
		name: "[Gen 9] National Dex BU",
		mod: "gen9",
		ruleset: ["[Gen 9] National Dex UU"],
		banlist: ["ND UU", "ND BUBL", "Slowbro-Base + Slowbronite", "Drought"],
	},
	{
		name: "[Gen 9] National Dex RU",
		mod: "gen9",
		ruleset: ["[Gen 9] National Dex BU"],
		banlist: ["ND BU", "ND RUBL"],
	},
	{
		name: "[Gen 9] National Dex NU",
		mod: "gen9",
		ruleset: ["[Gen 9] National Dex RU"],
		banlist: ["ND RU", "ND NUBL"],
	},
	{
		name: "[Gen 9] National Dex LC",
		mod: 'gen9',
		ruleset: ['Standard NatDex', 'Little Cup'],
		banlist: [
			'Moody', 'Eevium Z', 'King\'s Rock', 'Quick Claw', 'Razor Fang', 'Assist', 'Baton Pass', 'Dragon Rage', 'Sonic Boom',
		],
	},
	{
		name: "[Gen 9] National Dex Monotype",
		mod: "gen9",
		ruleset: [
			"Standard NatDex",
			"Baton Pass Stat Trap Clause",
			"Same Type Clause",
			"Terastal Clause",
			"Species Clause",
			"OHKO Clause",
			"Evasion Clause",
			"Sleep Clause Mod",
		],
		banlist: [
			"Annihilape",
			"Arceus",
			"Baxcalibur",
			"Blastoise-Mega",
			"Blaziken",
			"Blaziken-Mega",
			"Calyrex-Ice",
			"Calyrex-Shadow",
			"Chi-Yu",
			"Chien-Pao",
			"Darkrai",
			"Deoxys-Base",
			"Deoxys-Attack",
			"Dialga",
			"Dracovish",
			"Dragapult",
			"Espathra",
			"Eternatus",
			"Flutter Mane",
			"Frostiken-Mega",
			"Genesect",
			"Gengar-Mega",
			"Giratina",
			"Giratina-Origin",
			"Groudon",
			"Ho-Oh",
			"Hoopa-Unbound",
			"Iron Bundle",
			"Kangaskhan-Mega",
			"Kartana",
			"Kingambit",
			"Koraidon",
			"Kyogre",
			"Kyurem-Black",
			"Kyurem-White",
			"Lucario-Mega",
			"Lugia",
			"Lunala",
			"Magearna",
			"Marshadow",
			"Mawile-Mega",
			"Medicham-Mega",
			"Metagross-Mega",
			"Mewtwo",
			"Miraidon",
			"Naganadel",
			"Necrozma-Dawn-Wings",
			"Necrozma-Dusk-Mane",
			"Ogerpon-Hearthflame",
			"Palafin",
			"Palkia",
			"Pheromosa",
			"Rayquaza",
			"Reshiram",
			"Salamence-Mega",
			"Shaymin-Sky",
			"Solgaleo",
			"Spectrier",
			"Ursaluna-Bloodmoon",
			"Urshifu-Base",
			"Xerneas",
			"Yveltal",
			"Zacian",
			"Zacian-Crowned",
			"Zamazenta",
			"Zamazenta-Crowned",
			"Zekrom",
			"Zygarde-Base",
			"Zygarde-Complete",
			"Moody",
			"Shadow Tag",
			"Power Construct",
			"Booster Energy",
			"Damp Rock",
			"Focus Band",
			"Icy Rock",
			"King's Rock",
			"Leppa Berry",
			"Quick Claw",
			"Razor Fang",
			"Smooth Rock",
			"Terrain Extender",
			"Acupressure",
			"Baton Pass",
			"Last Respects",
			"Shed Tail",
			"Tricky Reception",
			"Caimanrago",
			"Cereblaze-Mega",
			"Forrogue-Mega",
			"Tempervian-Mega",
			"Wyrmperior-Mega",
			"Tempervian-Mega-Ashen"
		],
	},
	{
		name: "[Gen 9] National Dex AAA",
		desc: `Pok&eacute;mon have access to almost any ability.`,
		mod: 'gen9',
		searchShow: false,
		ruleset: ['Standard NatDex', '!Obtainable Abilities', 'Ability Clause = 2', 'Sleep Moves Clause', 'Terastal Clause'],
		banlist: [
			'Alakazam-Mega', 'Annihilape', 'Arceus', 'Archeops', 'Baxcalibur', 'Blacephalon', 'Blastoise-Mega', 'Blaziken-Mega', 'Calyrex-Ice', 'Calyrex-Shadow', 'Ceruledge', 'Chien-Pao', 'Darkrai', 'Deoxys-Attack',
			'Deoxys-Normal', 'Dialga', 'Dialga-Origin', 'Dracovish', 'Dragapult', 'Enamorus-Incarnate', 'Eternatus', 'Flutter Mane', 'Gengar-Mega', 'Giratina', 'Giratina-Origin', 'Gouging Fire', 'Groudon', 'Ho-Oh',
			'Hoopa-Unbound', 'Iron Boulder', 'Iron Bundle', 'Iron Valiant', 'Kangaskhan-Mega', 'Kartana', 'Keldeo', 'Kingambit', 'Koraidon', 'Kyogre', 'Kyurem', 'Kyurem-Black', 'Kyurem-White', 'Lucario-Mega', 'Lugia',
			'Lunala', 'Magearna', 'Marshadow', 'Melmetal', 'Mewtwo', 'Miraidon', 'Naganadel', 'Necrozma-Dawn-Wings', 'Necrozma-Dusk-Mane', 'Noivern', 'Palkia', 'Palkia-Origin', 'Pheromosa', 'Raging Bolt', 'Rayquaza',
			'Regigigas', 'Reshiram', 'Salamence-Mega', 'Shaymin-Sky', 'Shedinja', 'Slaking', 'Sneasler', 'Solgaleo', 'Spectrier', 'Urshifu', 'Urshifu-Rapid-Strike', 'Weavile', 'Xerneas', 'Xurkitree', 'Yveltal', 'Zacian',
			'Zacian-Crowned', 'Zekrom', 'Zeraora', 'Zygarde-50%', 'Arena Trap', 'Comatose', 'Contrary', 'Fur Coat', 'Good as Gold', 'Gorilla Tactics', 'Huge Power', 'Ice Scales', 'Illusion', 'Imposter', 'Innards Out',
			'Intrepid Sword', 'Magic Bounce', 'Magnet Pull', 'Moody', 'Neutralizing Gas', 'Orichalcum Pulse', 'Parental Bond', 'Poison Heal', 'Pure Power', 'Shadow Tag', 'Simple', 'Speed Boost', 'Stakeout', 'Triage',
			'Unburden', 'Water Bubble', 'Wonder Guard', 'King\'s Rock', 'Light Clay', 'Assist', 'Baton Pass', 'Electrify', 'Last Respects', 'Shed Tail',
		],
	},
	{
		name: "[Gen 9] National Dex Doubles",
		mod: "gen9",
		gameType: "doubles",
		ruleset: [
			"Standard NatDex",
			"Baton Pass Stat Trap Clause",
			"OHKO Clause",
			"Evasion Moves Clause",
			"Evasion Abilities Clause",
			"Species Clause",
			"Gravity Sleep Clause",
		],
		banlist: [
			"Annihilape",
			"Arceus",
			"Calyrex-Ice",
			"Calyrex-Shadow",
			"Dialga",
			"Dialga-Origin",
			"Eternatus",
			"Genesect",
			"Gengar-Mega",
			"Giratina",
			"Giratina-Origin",
			"Groudon",
			"Ho-Oh",
			"Koraidon",
			"Kyogre",
			"Kyurem-White",
			"Lugia",
			"Lunala",
			"Magearna",
			"Melmetal",
			"Mewtwo",
			"Miraidon",
			"Necrozma-Dawn-Wings",
			"Necrozma-Dusk-Mane",
			"Palkia",
			"Palkia-Origin",
			"Rayquaza",
			"Reshiram",
			"Shedinja",
			"Solgaleo",
			"Terapagos",
			"Urshifu-Base",
			"Xerneas",
			"Yveltal",
			"Zacian",
			"Zacian-Crowned",
			"Zamazenta-Crowned",
			"Zekrom",
			"Commander",
			"Power Construct",
			"Assist",
			"Coaching",
			"Dark Void",
			"Swagger",
		],
	},
	{
		name: "[Gen 9] National Dex AG",
		mod: "gen9",
		searchShow: false,
		ruleset: ["Standard NatDex"],
	},
	{
		name: "[Gen 9] National Dex BH",
		desc: `Balanced Hackmons with National Dex elements mixed in.`,
		mod: "gen9",
		searchShow: false,
		ruleset: [
			"-Nonexistent",
			"Standard NatDex",
			"Forme Clause",
			"Sleep Moves Clause",
			"Ability Clause = 2",
			"OHKO Clause",
			"Evasion Moves Clause",
			"Dynamax Clause",
			"CFZ Clause",
			"Terastal Clause",
			"!Obtainable",
		],
		banlist: [
			"Cramorant-Gorging",
			"Calyrex-Shadow",
			"Darmanitan-Galar-Zen",
			"Eternatus-Eternamax",
			"Groudon-Primal",
			"Rayquaza-Mega",
			"Shedinja",
			"Arena Trap",
			"Contrary",
			"Gorilla Tactics",
			"Huge Power",
			"Illusion",
			"Innards Out",
			"Magnet Pull",
			"Moody",
			"Neutralizing Gas",
			"Parental Bond",
			"Pure Power",
			"Shadow Tag",
			"Stakeout",
			"Water Bubble",
			"Wonder Guard",
			"Gengarite",
			"Berserk Gene",
			"Belly Drum",
			"Bolt Beak",
			"Chatter",
			"Double Iron Bash",
			"Electrify",
			"Last Respects",
			"Octolock",
			"Rage Fist",
			"Revival Blessing",
			"Shed Tail",
			"Shell Smash",
			"Comatose + Sleep Talk",
			"Imprison + Transform",
		],
		restricted: ["Arceus"],
		onValidateTeam(team, format) {
			// baseSpecies:count
			const restrictedPokemonCount = new Map<string, number>();
			for (const set of team) {
				const species = this.dex.species.get(set.species);
				if (!this.ruleTable.isRestrictedSpecies(species)) continue;
				restrictedPokemonCount.set(
					species.baseSpecies,
					(restrictedPokemonCount.get(species.baseSpecies) || 0) + 1
				);
			}
			for (const [baseSpecies, count] of restrictedPokemonCount) {
				if (count > 1) {
					return [
						`You are limited to one ${baseSpecies} forme.`,
						`(You have ${count} ${baseSpecies} forme${count === 1 ? "" : "s"
						}.)`,
					];
				}
			}
		},
	},
	//{
	//	name: "[Gen 9] Custom Game",
	//	mod: 'gen9',
	//	searchShow: false,
	//	debug: true,
	//	battle: {trunc: Math.trunc},
	//	ruleset: ['Team Preview', 'Cancel Mod', 'Max Team Size = 24', 'Max Move Count = 24', 'Max Level = 9999', 'Default Level = 100'],
	//}
];
